### ISSUE TITLE
Issue B2: Backend Controller for CRUD operations for announcements

### ISSUE THREAD

**Issue by jtanggy** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-1#25]
Developer Story:

As an developer
I have access to backend endpoints (through swagger) for CRUD operations for the Announcements table
So that I can build future features using this table
Acceptance Criteria:

 The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
 The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
 There is a GET endpoint to get all announcements for a specified commons
 There is a GET endpoint to get an announcement by its individual id number
 There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoint.
 There is a DELETE endpoint that allows deleting an announcement

**Comment by alexanderthomasucsb** [comment]
lgtm.
